SELECT 
	YEAR(order_date),
	SUM(sales_amount) AS TOTAL_SALES,
	COUNT(customer_key) AS TOTAL_CUSTOMERS,
	SUM(QUANTITY) AS TOTAL_QUANTITY
  FROM [DataWarehouseAnalytics].[gold].[fact_sales]
  where order_date is not null
  GROUP BY YEAR(order_date)
  order by YEAR(order_date)

  
  SELECT 
	YEAR(order_date),
	MONTH(order_date),
	SUM(sales_amount) AS TOTAL_SALES,
	COUNT(DISTINCT customer_key) AS TOTAL_CUSTOMERS,
	SUM(QUANTITY) AS TOTAL_QUANTITY
  FROM [DataWarehouseAnalytics].[gold].[fact_sales]
  where order_date is not null
  GROUP BY YEAR(order_date),MONTH(order_date)
  order by YEAR(order_date), MONTH(order_date)
   
--USING DATETRUNC FUNCTION
 SELECT 
	DATETRUNC(MONTH, order_date),
	SUM(sales_amount) AS TOTAL_SALES,
	COUNT(DISTINCT customer_key) AS TOTAL_CUSTOMERS,
	SUM(QUANTITY) AS TOTAL_QUANTITY
  FROM [DataWarehouseAnalytics].[gold].[fact_sales]
  where order_date is not null
  GROUP BY DATETRUNC(MONTH, order_date)
  order by DATETRUNC(MONTH, order_date)
   
--using format
 SELECT 
	FORMAT(order_date, 'yyyy-MM'),
	SUM(sales_amount) AS TOTAL_SALES,
	COUNT(DISTINCT customer_key) AS TOTAL_CUSTOMERS,
	SUM(QUANTITY) AS TOTAL_QUANTITY
  FROM [DataWarehouseAnalytics].[gold].[fact_sales]
  where order_date is not null
  GROUP BY FORMAT(order_date, 'yyyy-MM')
  order by FORMAT(order_date, 'yyyy-MM')

--CUMULATIVE ANALYSIS, AGGREGATE DATA PROGRESSIVELY OVERTIME, HELPS US 
--SEE WETHER BUSINESS IS GROWING OR DECLINING.

--TOTAL SALES PER MONTH AND 
--RUNNING TOTAL

SELECT 
	ORDER_DATE,
	TOTAL_SALES,
	SUM(TOTAL_SALES) OVER (ORDER BY ORDER_DATE) AS RUNNING_TOTAL_SALES
FROM 
(
SELECT 
	DATETRUNC(MONTH, ORDER_DATE) AS ORDER_DATE,
	SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(MONTH, ORDER_DATE)

) T

SELECT 
	ORDER_DATE,
	TOTAL_SALES,
	AVG_PRICE,
	SUM(TOTAL_SALES) OVER (ORDER BY ORDER_DATE) AS RUNNING_TOTAL_SALES,
	AVG(AVG_PRICE) OVER(ORDER BY ORDER_DATE) AS MOVING_AVG_PRICE
FROM 
(
SELECT 
	DATETRUNC(MONTH, ORDER_DATE) AS ORDER_DATE,
	SUM(SALES_AMOUNT) AS TOTAL_SALES,
	AVG(PRICE) AS AVG_PRICE
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(MONTH, ORDER_DATE)

) T

--comparing a value to a target value 

SELECT *
FROM gold.fact_sales F
LEFT JOIN gold.dim_products P
ON F.product_key = P.product_key

--COMPARING SALES TO AVERAGE SALES PERFOEMANCE
WITH YEARLY_PRODUCT_SALES AS (
SELECT YEAR(F.order_date) AS ORDER_YEAR,
		P.product_name,
		SUM(F.sales_amount) AS CURRENT_SALES
FROM gold.fact_sales F
LEFT JOIN gold.dim_products P
ON F.product_key = P.product_key
WHERE order_date IS NOT NULL
GROUP BY YEAR(F.order_date), P.product_name
)

SELECT 
	ORDER_YEAR,
	product_name,
	CURRENT_SALES,
	AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) AS AVG_SALES,
	CURRENT_SALES - AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) AS DIFF_AVG_SALES,
	CASE WHEN CURRENT_SALES - AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) > 0 THEN 'ABOVE AVERAGE'
		 WHEN CURRENT_SALES - CURRENT_SALES - AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) < 0 THEN 'BELOW AVERAGE'
		 ELSE 'AVG'
	END AS AVG_CHNG

FROM YEARLY_PRODUCT_SALES
order BY product_name, ORDER_YEAR



--COMPARING SALES TO PREVIOUS SALES PERFOEMANCE
WITH YEARLY_PRODUCT_SALES AS (
SELECT YEAR(F.order_date) AS ORDER_YEAR,
		P.product_name,
		SUM(F.sales_amount) AS CURRENT_SALES
FROM gold.fact_sales F
LEFT JOIN gold.dim_products P
ON F.product_key = P.product_key
WHERE order_date IS NOT NULL
GROUP BY YEAR(F.order_date), P.product_name
)

SELECT 
	ORDER_YEAR,
	product_name,
	CURRENT_SALES,
	AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) AS AVG_SALES,
	CURRENT_SALES - AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) AS DIFF_AVG_SALES,
	CASE WHEN CURRENT_SALES - AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) > 0 THEN 'ABOVE AVERAGE'
		 WHEN CURRENT_SALES - CURRENT_SALES - AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) < 0 THEN 'BELOW AVERAGE'
		 ELSE 'AVG'
	END AS AVG_CHNG,
	LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) AS PREVIOUS_YR_SALES,
	CURRENT_SALES - LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) as diff_prev_yr,
	CASE WHEN CURRENT_SALES - LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) > 0 THEN 'INCREASE'
		 WHEN CURRENT_SALES - CURRENT_SALES - LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) < 0 THEN 'DECREASE'
		 ELSE 'NO CHANGE'
	END AS PREV_YR_CHNG

FROM YEARLY_PRODUCT_SALES
order BY product_name, ORDER_YEAR


--COMPARING SALES TO PREVIOUS SALES PERFOEMANCE
WITH YEARLY_PRODUCT_SALES AS (
SELECT MONTH(F.order_date) AS ORDER_YEAR,
		P.product_name,
		SUM(F.sales_amount) AS CURRENT_SALES
FROM gold.fact_sales F
LEFT JOIN gold.dim_products P
ON F.product_key = P.product_key
WHERE order_date IS NOT NULL
GROUP BY MONTH(F.order_date), P.product_name
)

SELECT 
	ORDER_YEAR,
	product_name,
	CURRENT_SALES,
	AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) AS AVG_SALES,
	CURRENT_SALES - AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) AS DIFF_AVG_SALES,
	CASE WHEN CURRENT_SALES - AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) > 0 THEN 'ABOVE AVERAGE'
		 WHEN CURRENT_SALES - CURRENT_SALES - AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) < 0 THEN 'BELOW AVERAGE'
		 ELSE 'AVG'
	END AS AVG_CHNG,
	LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) AS PREVIOUS_YR_SALES,
	CURRENT_SALES - LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) as diff_prev_yr,
	CASE WHEN CURRENT_SALES - LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) > 0 THEN 'INCREASE'
		 WHEN CURRENT_SALES - CURRENT_SALES - LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) < 0 THEN 'DECREASE'
		 ELSE 'NO CHANGE'
	END AS PREV_YR_CHNG

FROM YEARLY_PRODUCT_SALES
order BY product_name, ORDER_YEAR


--PART TO WHOLE ANALYSIS
with category_sales as 
(
SELECT 
	CATEGORY,
	SUM(sales_amount) AS TOTAL_SALES

FROM gold.fact_sales F
LEFT JOIN gold.dim_products P
ON P.product_key = F.product_key
GROUP BY category
)

SELECT 
	CATEGORY,
	TOTAL_SALES,
	SUM(TOTAL_SALES) OVER () AS OVER_ALL_SALES,
	CONCAT(ROUND((CAST(TOTAL_SALES AS FLOAT)/SUM(TOTAL_SALES) OVER()) *100,2),'%') AS PERCENTAGE_OF_TOTAL

FROM category_sales

--DATA SEGMENTATION 
SELECT 
		product_key,
		product_name,
		cost,
	CASE WHEN cost< 100 THEN 'BELOW 100'
		 WHEN COST BETWEEN 100 AND 500 THEN '100-500'
		 WHEN COST BETWEEN 500 AND 1000 THEN '500-1000'
		 ELSE 'ABOVE 1000'
	END AS COST_RANGE

FROM gold.dim_products

--COUNT HOW MANY PRODUCTS FALL INTO EACH SEGMENT, USING CTE
WITH PRODUCT_SEGMENT AS 
(
SELECT 
		product_key,
		product_name,
		cost,
	CASE WHEN cost< 100 THEN 'BELOW 100'
		 WHEN COST BETWEEN 100 AND 500 THEN '100-500'
		 WHEN COST BETWEEN 500 AND 1000 THEN '500-1000'
		 ELSE 'ABOVE 1000'
	END AS COST_RANGE

FROM gold.dim_products)

SELECT COST_RANGE,
	   COUNT(product_key) AS TOTAL_PRODUCTS,
	   SUM(COST)

FROM PRODUCT_SEGMENT
GROUP BY COST_RANGE
ORDER BY TOTAL_PRODUCTS DESC


WITH CUSTOMER_SPENDING AS (
SELECT 
C.CUSTOMER_KEY,
SUM(F.SALES_AMOUNT) AS TOTAL_SPENDING,
MIN(ORDER_DATE) AS FIRST_ORDER,
MAX(ORDER_DATE) AS LAST_ORDER,
DATEDIFF(MONTH,MIN(ORDER_DATE), MAX(ORDER_DATE)) AS LIFE_SPAN
FROM GOLD.fact_sales F
LEFT JOIN GOLD.dim_customers C
ON F.customer_key = C.customer_key
GROUP BY C.customer_key
)

SELECT 
	CUSTOMER_KEY,
	TOTAL_SPENDING,
	LIFE_SPAN,
	CASE WHEN LIFE_SPAN >= 12 AND TOTAL_SPENDING > 5000 THEN 'VIP'
		 WHEN LIFE_SPAN >= 12 AND TOTAL_SPENDING <= 5000 THEN 'REGULAR'
	ELSE 'NEW'
	END AS CUSTOMER_SEGMENT,
	COUNT(CUSTOMER_KEY) AS TOTAL_CUSTOMER
FROM CUSTOMER_SPENDING



WITH CUSTOMER_SPENDING AS (
	SELECT 
	C.CUSTOMER_KEY,
	SUM(F.SALES_AMOUNT) AS TOTAL_SPENDING,
	MIN(ORDER_DATE) AS FIRST_ORDER,
	MAX(ORDER_DATE) AS LAST_ORDER,
	DATEDIFF(MONTH,MIN(ORDER_DATE), MAX(ORDER_DATE)) AS LIFE_SPAN
	FROM GOLD.fact_sales F
	LEFT JOIN GOLD.dim_customers C
	ON F.customer_key = C.customer_key
	GROUP BY C.customer_key
)


SELECT CUSTOMER_SEGMENT,
	   COUNT(CUSTOMER_KEY) AS TOTAL_CUSTOMERS
FROM 
(
	SELECT 
		CUSTOMER_KEY,
		CASE WHEN LIFE_SPAN >= 12 AND TOTAL_SPENDING > 5000 THEN 'VIP'
			 WHEN LIFE_SPAN >= 12 AND TOTAL_SPENDING <= 5000 THEN 'REGULAR'
		ELSE 'NEW'
		END AS CUSTOMER_SEGMENT
	FROM CUSTOMER_SPENDING

)T
GROUP BY CUSTOMER_SEGMENT
ORDER BY TOTAL_CUSTOMERS DESC



CREATE VIEW GOLD.REPORT_CUSTOMER AS 
WITH BASE_QUERY AS
(
SELECT 
	F.order_number,
	F.product_key,
	F.order_date,
	F.sales_amount,
	F.quantity,
	C.customer_key,
	C.customer_number,
	CONCAT(C.first_name,' ', C.last_name)AS CUSTOMER_NAME,
	C.birthdate,
	DATEDIFF(YEAR, C.birthdate, GETDATE()) AS AGE
FROM gold.fact_sales F
LEFT JOIN GOLD.dim_customers C
ON C.customer_key = F.customer_key
WHERE order_date IS NOT NULL
), CUSTOMER_AGGREGATION AS
(
SELECT 
	customer_key,
	customer_number,
	CUSTOMER_NAME,
	birthdate,
	AGE,
	COUNT(DISTINCT ORDER_NUMBER) AS TOTAL_ORDERS,
	SUM(SALES_AMOUNT) AS TOTAL_SALES,
	COUNT(DISTINCT PRODUCT_KEY) AS TOTAL_PRODUCTS,
	MAX(order_date) AS LAST_ORDER_DATE,
	DATEDIFF(MONTH, MIN(ORDER_DATE), MAX(ORDER_DATE)) AS LIFE_SPAN

FROM BASE_QUERY
GROUP BY 
	customer_key,
	customer_number,
	CUSTOMER_NAME,
	birthdate,
	AGE
)

SELECT 
	customer_key,
	customer_number,
	CUSTOMER_NAME,
	birthdate,
	AGE,
	CASE WHEN AGE < 20 THEN 'UNDER 20'
		 WHEN AGE BETWEEN 20 AND 40 THEN '20-29'
		 WHEN AGE BETWEEN 30 AND 39 THEN '30-39'
		 WHEN AGE BETWEEN 40 AND 49 THEN '40-49'
		 ELSE '50 AND ABOVE'
	END AS AGE_GROUP,
	CASE WHEN LIFE_SPAN >= 12 AND TOTAL_SALES > 5000 THEN 'VIP'
			 WHEN LIFE_SPAN >= 12 AND TOTAL_SALES <= 5000 THEN 'REGULAR'
		ELSE 'NEW'
	END AS CUSTOMER_SEGMENT,
	LAST_ORDER_DATE,
	DATEDIFF(MONTH, LAST_ORDER_DATE, GETDATE()) AS RECENCY,
	TOTAL_ORDERS,
	TOTAL_SALES,
	TOTAL_PRODUCTS,
	LIFE_SPAN,
	--COMPUTE AVERAGE ORDER VALUE(AVO)
	CASE WHEN TOTAL_ORDERS = 0 THEN 0
		 ELSE TOTAL_SALES/TOTAL_ORDERS 
	END AS AVG_ORDER_VALUE,
	CASE WHEN LIFE_SPAN = 0 THEN 0
		 ELSE TOTAL_SALES / LIFE_SPAN
	END AS AVG_MONTHLY_SPEND

FROM CUSTOMER_AGGREGATION


SELECT AGE_GROUP,
	   COUNT(customer_number) AS TOTAL_CUSTOMER,
	   SUM(TOTAL_SALES) AS TOTAL_SALES

FROM gold.REPORT_CUSTOMER
GROUP BY AGE_GROUP

SELECT 
	   CUSTOMER_SEGMENT,
	   COUNT(customer_number) AS TOTAL_CUSTOMER,
	   SUM(TOTAL_SALES) AS TOTAL_SALES

FROM gold.REPORT_CUSTOMER
GROUP BY CUSTOMER_SEGMENT