
SELECT *,
	CURRENT_MONTH_SALES - PREVIOUS_MONTH_SALES AS MNTH_CHANGE,
	CAST((CURRENT_MONTH_SALES - PREVIOUS_MONTH_SALES) AS FLOAT)/PREVIOUS_MONTH_SALES *100
FROM 
(
SELECT 
	MONTH(OrderDate) AS ORDERMONTH,
	SUM(SALES) CURRENT_MONTH_SALES,
	LAG(SUM(Sales)) OVER(ORDER BY MONTH(ORDERDATE)) AS PREVIOUS_MONTH_SALES
FROM Sales.Orders
GROUP BY MONTH(OrderDate)
)T


--CUSTOMER RETENTION ANALYSIS
SELECT CustomerID,
		AVG(DAYS_UNT_NEXT_ORDER)
FROM
(

SELECT 
	ORDERID,
	CustomerID,
	OrderDate CURRENT_ORDER,
	LEAD(OrderDate) OVER(PARTITION BY CUSTOMERID ORDER BY ORDERDATE) NEXT_ORDER,
	DATEDIFF(DAY, OrderDate, 	LEAD(OrderDate) OVER(PARTITION BY CUSTOMERID ORDER BY ORDERDATE)) DAYS_UNT_NEXT_ORDER

FROM Sales.Orders
--ORDER BY CustomerID, OrderDate
)T
GROUP BY CustomerID


select 
	ORDERID,
	PRODUCTID,
	Sales,
	FIRST_VALUE(SALES) OVER (PARTITION BY PRODUCTID ORDER BY SALES) LOWESTSALES

FROM Sales.Orders