SELECT TOP (1000) [order_number]
      ,[product_key]
      ,[customer_key]
      ,[order_date]
      ,[shipping_date]
      ,[due_date]
      ,[sales_amount]
      ,[quantity]
      ,[price]
  FROM [DataWarehouseAnalytics].[gold].[fact_sales];


WITH CTE AS (
SELECT 
	DATETRUNC(MONTH, ORDER_DATE) AS ORDER_DATE,
	SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM GOLD.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(MONTH, ORDER_DATE)
)

 SELECT ORDER_DATE,
	     TOTAL_SALES,
	    SUM(TOTAL_SALES) OVER (ORDER BY ORDER_DATE ) AS RUNNING_TOTAL_SALES
FROM CTE


WITH CTE2 AS (
SELECT 
	DATETRUNC(MONTH, ORDER_DATE) AS ORDER_DATE,
	SUM(SALES_AMOUNT) AS TOTAL_SALES,
	AVG(PRICE) AS AVG_PRICE
FROM GOLD.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(MONTH, ORDER_DATE)
)

 SELECT ORDER_DATE,
	     TOTAL_SALES,
		 AVG_PRICE,
	    SUM(TOTAL_SALES) OVER (ORDER BY ORDER_DATE ) AS RUNNING_TOTAL_SALES,
		AVG(AVG_PRICE) OVER (ORDER BY ORDER_DATE ) AS MOVING_AVG_PRICE

FROM CTE2


--PERFORMANCE ANALYSIS
SELECT * FROM GOLD.fact_sales
SELECT * FROM GOLD.dim_products

SELECT 
	YEAR(F.ORDER_DATE) AS ORDER_YEAR,
	P.PRODUCT_NAME,
	SUM(F.SALES_AMOUNT) AS CURRENT_SALES
	FROM GOLD.fact_sales F
	LEFT JOIN GOLD.dim_PRODUCTS P
	ON F.PRODUCT_KEY = P.PRODUCT_KEY
	WHERE F.order_date IS NOT NULL
	GROUP BY 
	YEAR(F.ORDER_DATE),
	P.product_name