

SELECT ORDER_DATE,
	   TOTAL_SALES,
	   SUM(TOTAL_SALES) OVER (ORDER BY ORDER_DATE ) AS RUNNING_TOTAL_SALES

FROM (
SELECT 
	DATETRUNC(MONTH, ORDER_DATE) AS ORDER_DATE,
	SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM GOLD.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(MONTH, ORDER_DATE)
)