SELECT * from LOAN
where address_state in ('GA', 'TX','MI') 
AND annual_income > 75000

SELECT YEAR(ISSUE_DATE) FROM LOAN
SELECT MONTH(ISSUE_DATE) FROM LOAN

SELECT ADDRESS_STATE, SUM(total_payment) FROM LOAN
GROUP BY address_state

SELECT YEAR(ISSUE_DATE) FROM LOAN
SELECT MONTH(ISSUE_DATE) FROM LOAN


SELECT * from LOAN

SELECT address_state, EMP_TITLE,HOME_OWNERSHIP,
		ROW_NUMBER() OVER (PARTITION BY HOME_OWNERSHIP ORDER BY ADDRESS_STATE )
FROM LOAN


SELECT loan_amount, total_acc, ROUND(int_rate, 2)

from LOAN

SELECT application_type, home_ownership,annual_income,
	   LAG(ANNUAL_INCOME, 1) OVER(PARTITION BY HOME_OWNERSHIP ORDER BY ISSUE_DATE)
from LOAN

SELECT application_type, home_ownership,annual_income,
	   LEAD(ANNUAL_INCOME, 1) OVER(PARTITION BY HOME_OWNERSHIP ORDER BY ISSUE_DATE)
from LOAN


SELECT *
from LOAN

SELECT VERIFICATION_STATUS, SUM(ANNUAL_INCOME) OVER (PARTITION BY VERIFICATION_STATUS) FROM LOAN;

SELECT  home_ownership, VERIFICATION_STATUS, AVG(ANNUAL_INCOME) OVER (PARTITION BY home_ownership) FROM LOAN;

SELECT VERIFICATION_STATUS, MIN(ANNUAL_INCOME) OVER (PARTITION BY VERIFICATION_STATUS) FROM LOAN;

SELECT VERIFICATION_STATUS, MAX(ANNUAL_INCOME) OVER (PARTITION BY VERIFICATION_STATUS) FROM LOAN;